### ISSUE TITLE
config.mask_time_prob=0.5

### ISSUE THREAD

**Issue by WhXmURandom** [nikvaessen/w2v2-speaker-few-samples#1]
Hi,I have a question and I hope you can answer it.Your paper describes "For wav2vec2, we use a LayerDrop of 10% in the transformer layers, and a dropout of 10% is applied after each fully-connected layer in the network. Wav2vec2 also applies masking before the relative positional embedding is added, similar to SpecAugment; 10% of the channel dimensions are randomly masked, and 50% of the time dimensions are randomly masked."
BUT in the "w2v2-speaker-few-samples/tree/master/src/networks/wav2vec2_components/base_components.py", mask_time_prob is set to 0.05 and mask_feature_prob is set to 0.

**Comment by nikvaessen** [comment]
See https://github.com/nikvaessen/w2v2-speaker-few-samples/blob/master/config/network/regularisation/wav2vec2_default.yaml

**Comment by WhXmURandom** [comment]
I got it, thank you.
